name: 'mono-deployer'
description: 'Single line deploy action to use within leadsforce monorepo'

inputs:
  repo:
    description: 'Repository name'
    required: true
  folder:
    description: 'Which folder to use'
    required: true
  tag:
    description: 'Package tag'
    required: true
  token:
    description: 'GitHub Personal Access Token with package write permissions'
    required: true
  user:
    description: 'GitHub User'
    required: true
  ghcr_secret:
    description: 'GHCR KUBE SECRET'
    required: true
  kubeconfig:
    description: 'Kubeconfig content'
    required: true
  pool_id:
    description: "Linode pool id"
    required: true
  envs:
    description: "Helm envs --set"
    required: true

runs:
  using: "composite"
  steps:
    -
      uses: leadsforce/action_build_monorepo@v1
      with:
        repo: ${{ inputs.repo }}
        folder: ${{ inputs.folder }}
        tag: ${{ inputs.tag }}
        token: ${{ inputs.token }}
        user: ${{ inputs.user }}
    -
      name: Setup k8s context
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo "${{ inputs.kubeconfig }}" >> ~/.kube/config
        chmod 600 ~/.kube/config
    - uses: azure/setup-kubectl@v3
    - uses: azure/setup-helm@v3
    -
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
    -
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ inputs.kubeconfig }}
    -
      name: Deploy to k8s cluster
      shell: bash
      run: |
        APP_NAME=$(echo ${{ inputs.folder }} | tr '_' '-')
        APP_NS=$(echo "${{ inputs.repo }}" | tr '_' '-')
        NS="$APP_NS-${{ inputs.tag }}"
        kubectl create ns $NS || echo "Already created"
        kubectl label namespace nats istio-injection=enabled --overwrite || echo "Already labeled"
        DOCKER_REPO="ghcr.io/${{ github.repository_owner }}/${{ inputs.repo }}_${{ inputs.folder }}:${{ inputs.tag }}"
        helm upgrade --install $APP_NAME ${{ inputs.folder }}/platform/chart/ \
        -n $NS
        --set image.repository="$DOCKER_REPO" \
        --set image.tag="${{ inputs.tag }}" \
        ${{ inputs.envs }} \
        --set registries[0].name="github-registry-secret" \
        --set registries[0].key="${{ inputs.ghcr_secret }}" \
        \
        --set-string nodeSelector."lke\\.linode\\.com/pool-id"="${{ inputs.pool_id }}" \
