name: 'mono-deployer'
description: 'Single line deploy action to use within leadsforce monorepo'

inputs:
  repo:
    description: 'Repository name'
    required: true
  folder:
    description: 'Which folder to use'
    required: true
  tag:
    description: 'Package tag'
    required: true
  token:
    description: 'GitHub Personal Access Token with package write permissions'
    required: true
  user:
    description: 'GitHub User'
    required: true
  ghcr_secret:
    description: 'GHCR KUBE SECRET'
    required: true
  kubeconfig:
    description: 'Kubeconfig content'
    required: true
  pool_id:
    description: "Linode pool id"
    required: true
  envs:
    description: "Helm envs --set"
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.user }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: "{{defaultContext}}:${{ inputs.folder }}"
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.repo }}_${{ inputs.folder }}:${{ inputs:tag }}
        cache-from: type=registry,ref=${{ inputs.repo }}_${{ inputs.folder }}:${{ inputs.tag }}
        cache-to: type=inline
        build-args: |
          NPM_TOKEN=${{ inputs.token }}
    -
      name: Setup k8s context
      run: |
        mkdir -p ~/.kube
        echo "${{ inputs.kubeconfig }}" >> ~/.kube/config
        chmod 600 ~/.kube/config
    -
      name: Install helm
      uses: azure/setup-helm@v3
    -
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
    - name: Deploy to k8s cluster
      run: |
        APP_NAME=$(echo ${{ inputs.folder }} | tr '_' '-')
        APP_NS=$(echo "${{ inputs.repo }}" | tr '_' '-')
        DOCKER_REPO="ghcr.io/${{ github.repository_owner }}/${{ inputs.repo }}_${{ inputs.folder }}:${{ inputs:tag }}"
        helm upgrade --install $APP_NAME ${{ inputs.folder }}/platform/chart/ \
        --create-namespace \
        -n $APP_NS-${{ inputs.tag }} \
        --set image.repository="$DOCKER_REPO" \
        --set image.tag="${{ inputs.tag }}" \
        \
        ${{ inputs.envs }}
        \
        --set registries[0].name="github-registry-secret" \
        --set registries[0].key="${{ inputs.ghcr_secret }}" \
        \
        --set-string nodeSelector."lke\\.linode\\.com/pool-id"="${{ inputs.pool_id }}" \
